// Generates the feed catalogue for the docs from the committee config templates
// (apps/publisher/configs) and the testnet deployment record:
//   src/data/committees.json            data for <FeedDetail> and <CommitteeDetail>
//   content/docs/feeds/<feed>.mdx       one page per feed
// Run: node scripts/gen-feeds.mjs (also runs before dev and build).
import { mkdirSync, readFileSync, writeFileSync, readdirSync, unlinkSync } from "node:fs";

const root = new URL("../../../", import.meta.url);
const read = (p) => JSON.parse(readFileSync(new URL(p, root), "utf8"));
const deployment = read("deployments/testnet.json");

const VENUE = { binance: "Binance", coinbase: "Coinbase", kraken: "Kraken", bitstamp: "Bitstamp", okx: "OKX", bybit: "Bybit", gate: "Gate", bitget: "Bitget", kucoin: "KuCoin", mexc: "MEXC", upbit: "Upbit" };

// What kind of market a feed prices, and what that means for a consumer.
function category(symbol) {
  if (symbol === "Crypto.USDT/USD") return { name: "Stablecoin rate", note: "Tracks the USDT peg. Use it to convert /USDT prices to USD, and watch it for depegs." };
  if (symbol.startsWith("Crypto.CKB/")) return { name: "Thinner liquidity", note: "CKB trades on fewer venues with less depth than the majors. Prices move more between ticks and confidence is wider; set conservative bounds." };
  return { name: "Deep liquidity", note: "Among the most traded crypto markets, priced from several large exchanges." };
}

const committees = {};
const feeds = [];
for (const name of ["majors"]) {
  const t = read(`apps/publisher/configs/${name}.template.json`);
  const c = deployment.committees[name];
  committees[name] = {
    name,
    typeHash: c.typeHash,
    typeScript: c.typeScript,
    publishers: c.publishers,
    quorum: Math.floor((2 * c.publishers) / 3) + 1,
    tickPeriodMs: t.tickPeriodMs,
    createdAt: c.createdAt,
    feeds: t.feeds.map((f) => f.symbol),
  };
  for (const f of t.feeds) {
    if (f.twap) {
      // A TWAP feed (docs/designs/twap60.md): no exchanges of its own, priced from its source feed.
      const [base, rest] = f.symbol.replace("Crypto.", "").split("/");
      const quote = rest.split(".")[0];
      const suffix = f.symbol.split(".").at(-1);
      feeds.push({
        symbol: f.symbol,
        pair: `${base}/${quote} ${suffix}`,
        base,
        quote,
        slug: `${base}-${quote}-${suffix}`.toLowerCase(),
        committee: name,
        tickPeriodMs: t.tickPeriodMs,
        expo: f.expo,
        toleranceBps: f.toleranceBps,
        emaHalfLifeMs: f.emaHalfLifeMs,
        twap: f.twap,
        markets: [],
        category: { name: "Settlement price", note: `The average of ${f.twap.source.replace("Crypto.", "")}'s finalized one-second prices over ${f.twap.windowMs / 1000} s, signed once every ${f.twap.everyMs / 1000} s. Moving it means holding the market off for the whole window, so settle on it rather than on a single second.` },
      });
      continue;
    }
    const [base, quote] = f.symbol.replace("Crypto.", "").split("/");
    feeds.push({
      symbol: f.symbol,
      pair: `${base}/${quote}`,
      base,
      quote,
      slug: `${base}-${quote}`.toLowerCase(),
      committee: name,
      tickPeriodMs: t.tickPeriodMs,
      expo: f.expo,
      method: f.method,
      windowMs: f.windowMs,
      maxQuoteAgeMs: f.maxQuoteAgeMs,
      maxSpreadBps: f.maxSpreadBps,
      maxDeviationBps: f.maxDeviationBps,
      minVenues: f.minVenues,
      minTopNotional: f.minTopNotional,
      toleranceBps: f.toleranceBps,
      emaHalfLifeMs: f.emaHalfLifeMs,
      markets: f.markets.map((m) => ({ venue: VENUE[m.venue] ?? m.venue, market: m.market })),
      category: category(f.symbol),
    });
  }
}

mkdirSync(new URL("../src/data/", import.meta.url), { recursive: true });
writeFileSync(new URL("../src/data/committees.json", import.meta.url), `${JSON.stringify({ committees, feeds }, null, 2)}\n`);

const dir = new URL("../content/docs/feeds/", import.meta.url);
mkdirSync(dir, { recursive: true });
for (const f of readdirSync(dir)) if (f.endsWith(".mdx") && f.includes("-")) unlinkSync(new URL(f, dir));
for (const f of feeds) {
  if (f.twap) {
    const source = f.twap.source.replace("Crypto.", "");
    const sourceSlug = source.replace("/", "-").toLowerCase();
    writeFileSync(
      new URL(`${f.slug}.mdx`, dir),
      `---
title: ${f.pair}
description: The ${f.twap.windowMs / 1000} s average of ${source}, signed once every ${f.twap.everyMs / 1000} s by the ${f.committee} committee.
---

{/* Generated by scripts/gen-feeds.mjs from apps/publisher/configs/${f.committee}.template.json. Do not edit. */}

<FeedDetail symbol="${f.symbol}" />

## About this feed

- **${f.category.name}.** ${f.category.note}
- It is published only at boundary ticks: the update whose publish time is a multiple of ${f.twap.everyMs / 1000} s. To settle "at 12:05", read the update with publish time 12:05:00.
- The update at boundary \`t\` averages the finalized [${source}](/docs/feeds/${sourceSlug}) prices from \`t − ${f.twap.windowMs / 1000 + 1} s\` to \`t − 2 s\`, each second weighted equally. It is about 2 s older than its timestamp.
- If fewer than ${f.twap.minTicks} of those seconds have a price, that boundary has no TWAP: treat it as VOID. A leader can also leave a boundary without a TWAP; contracts should define what a missing boundary means (for example, use the next one).
- conf is the larger of the window's average conf and how much the price moved within it.
`,
    );
    continue;
  }
  const quoteNote =
    f.quote === "USDT" ? `Quoted in USDT (Tether), not US dollars. For a USD price, multiply by [USDT/USD](/docs/feeds/usdt-usd).`
    : f.quote === "USDC" ? `Quoted in USDC, not US dollars. There is no USDC/USD feed yet: only two exchanges trade it directly.`
    : `Quoted in US dollars, from exchanges with direct USD markets.`;
  writeFileSync(
    new URL(`${f.slug}.mdx`, dir),
    `---
title: ${f.pair}
description: ${f.base} priced in ${f.quote}, signed every ${f.tickPeriodMs / 1000} s by the ${f.committee} committee from ${f.markets.length} exchanges.
---

{/* Generated by scripts/gen-feeds.mjs from apps/publisher/configs/${f.committee}.template.json. Do not edit. */}

<FeedDetail symbol="${f.symbol}" />

## About this feed

- **${f.category.name}.** ${f.category.note}
- ${quoteNote}
- A price needs at least ${f.minVenues} of the ${f.markets.length} exchanges below to be healthy in the same tick; otherwise the tick carries no ${f.pair} price.
`,
  );
}
writeFileSync(
  new URL("meta.json", dir),
  `${JSON.stringify({ title: "Feeds", description: "Every feed, committee and policy", root: true, pages: ["index", "committees", "policy", "---Feeds---", ...feeds.map((f) => f.slug)] }, null, 2)}\n`,
);
console.log(`gen-feeds: ${feeds.length} feeds, ${Object.keys(committees).length} committees`);
