//! Cross-language vectors in `vectors/protocol.json`, generated from the Rust codecs.
//! The TypeScript SDK asserts against the same file.
//!
//! Regenerate after an intentional format change:
//! `LEAN_WRITE_VECTORS=1 cargo test -p tests --target aarch64-apple-darwin vectors`

use lean_oracle_common::{
    price_feed::PriceFeedData,
    price_update::{leaf_hash, PriceMessage, PriceUpdateBlob},
    protocol_hash::{feed_id, type_id_seed},
    publisher_set::{PreviousSet, PublisherSetData, GOVERNANCE_PAUSED, OP_PAUSE, OP_REVOKE_PREVIOUS, OP_ROTATE, OP_ROTATE_REVOKE, OP_UNPAUSE},
};
use serde_json::{json, Value};

use crate::fixtures::*;

const PATH: &str = "../vectors/protocol.json";
const SYMBOLS: [&str; 6] = ["Crypto.BTC/USD", "Crypto.BTC/USDT", "Crypto.BTC/USDC", "Crypto.USDT/USD", "Crypto.CKB/USDT", "Crypto.CKB/USDC"];

fn hex(bytes: &[u8]) -> String {
    let body: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    format!("0x{body}")
}

fn message_json(m: &PriceMessage) -> Value {
    json!({
        "feedId": hex(&m.feed_id),
        "price": m.price.to_string(),
        "conf": m.conf.to_string(),
        "expo": m.expo,
        "prevPublishTimeMs": m.prev_publish_time_ms.to_string(),
        "emaPrice": m.ema_price.to_string(),
        "emaConf": m.ema_conf.to_string(),
        "sourceTimeMs": m.source_time_ms.to_string(),
        "numPublishers": m.num_publishers,
        "bytes": hex(&m.to_bytes()),
        "leafHash": hex(&leaf_hash(&m.to_bytes())),
    })
}

fn build() -> Value {
    let committee = Committee::new(4, 1);
    let next = Committee::new(4, 2);
    let set_type_hash = [0xbb; 32];
    let time = 1_700_000_400_000u64;
    let messages = vec![
        message(feed_id(b"Crypto.BTC/USD"), 6_789_012_345_678),
        message(feed_id(b"Crypto.ETH/USD"), 312_345_678_900),
        message(feed_id(b"Crypto.SOL/USD"), 15_012_345_678),
    ];
    let signers = committee.quorum_indexes();
    let blob = signed_update(&committee, set_type_hash, time, messages, &signers);
    let btc_index = blob.entries.iter().position(|e| e.message_bytes[1..33] == btc()).unwrap();
    let btc_only = PriceUpdateBlob { entries: vec![blob.entries[btc_index].clone()], ..blob.clone() };
    let btc_message = PriceMessage::from_bytes(&blob.entries[btc_index].message_bytes).unwrap();

    let feed_cell = PriceFeedData {
        feed_id: btc(),
        publisher_set_type_hash: set_type_hash,
        price: btc_message.price,
        conf: btc_message.conf,
        expo: btc_message.expo,
        publish_time_ms: time,
        prev_publish_time_ms: btc_message.prev_publish_time_ms,
        ema_price: btc_message.ema_price,
        ema_conf: btc_message.ema_conf,
        source_time_ms: btc_message.source_time_ms,
        num_publishers: btc_message.num_publishers,
        set_index: blob.header.set_index,
    };
    let first_input = [0x42u8; 44];
    // Governance digests are bound to the committee cell (its type hash).
    let committee_hash = set_type_hash;
    let next_data = PublisherSetData {
        governance_nonce: committee.data.governance_nonce + 1,
        current: next.data.current.clone(),
        previous: Some(PreviousSet { set: committee.data.current.clone(), until_ms: time + 1_000 }),
        ..committee.data.clone()
    };
    let revoke_data = PublisherSetData { previous: None, ..next_data.clone() };
    let paused = PublisherSetData { governance_nonce: committee.data.governance_nonce + 1, governance_flags: GOVERNANCE_PAUSED, ..committee.data.clone() };
    let unpaused = PublisherSetData { governance_nonce: paused.governance_nonce + 1, governance_flags: 0, ..paused.clone() };
    let revoked_previous = PublisherSetData { governance_nonce: next_data.governance_nonce + 1, previous: None, ..next_data.clone() };
    let rotation_auth = committee.sign(&committee.data.update_hash(&committee_hash, &next_data, OP_ROTATE), &signers);
    let rotation_pop = next.sign(&next_data.pop_hash(&committee_hash), &(0..4).collect::<Vec<_>>());

    json!({
        "description": "Generated by tests/src/vectors.rs from the Rust codecs. Do not edit by hand.",
        "feedIds": SYMBOLS.iter().map(|s| json!({ "symbol": s, "feedId": hex(&feed_id(s.as_bytes())) })).collect::<Vec<_>>(),
        "typeId": { "firstInput": hex(&first_input), "outputIndex": 1, "typeId": hex(&type_id_seed(&first_input, 1)) },
        "committee": {
            "privateKeys": committee.keys.iter().map(|k| hex(&k.to_bytes())).collect::<Vec<_>>(),
            "networkId": hex(&committee.data.network_id),
            "governanceNonce": committee.data.governance_nonce.to_string(),
            "governanceFlags": committee.data.governance_flags,
            "minRotationIntervalS": committee.data.min_rotation_interval_s.to_string(),
            "setIndex": committee.data.current.set_index,
            "pubkeys": committee.data.current.pubkeys.iter().map(|k| hex(k)).collect::<Vec<_>>(),
            "quorum": committee.data.current.quorum(),
            "bytes": hex(&committee.data.to_bytes()),
            "stateHash": hex(&committee.data.state_hash()),
        },
        "rotation": {
            "nextPrivateKeys": next.keys.iter().map(|k| hex(&k.to_bytes())).collect::<Vec<_>>(),
            "committeeTypeHash": hex(&committee_hash),
            "previousUntilMs": (time + 1_000).to_string(),
            "nextBytes": hex(&next_data.to_bytes()),
            "updateHash": hex(&committee.data.update_hash(&committee_hash, &next_data, OP_ROTATE)),
            "popHash": hex(&next_data.pop_hash(&committee_hash)),
            "authorizationBundle": hex(&rotation_auth.to_bytes()),
            "popBundle": hex(&rotation_pop.to_bytes()),
        },
        "governance": {
            "rotateRevoke": { "nextBytes": hex(&revoke_data.to_bytes()), "updateHash": hex(&committee.data.update_hash(&committee_hash, &revoke_data, OP_ROTATE_REVOKE)) },
            "pause": { "nextBytes": hex(&paused.to_bytes()), "updateHash": hex(&committee.data.update_hash(&committee_hash, &paused, OP_PAUSE)) },
            "unpause": { "nextBytes": hex(&unpaused.to_bytes()), "updateHash": hex(&paused.update_hash(&committee_hash, &unpaused, OP_UNPAUSE)) },
            "revokePrevious": { "nextBytes": hex(&revoked_previous.to_bytes()), "updateHash": hex(&next_data.update_hash(&committee_hash, &revoked_previous, OP_REVOKE_PREVIOUS)) },
        },
        "update": {
            "publisherSetTypeHash": hex(&set_type_hash),
            "setIndex": blob.header.set_index,
            "publishTimeMs": time.to_string(),
            "tickPeriodMs": blob.header.tick_period_ms,
            "configHash": hex(&blob.header.config_hash),
            "leafCount": blob.header.leaf_count,
            "merkleRoot": hex(&blob.header.merkle_root),
            "headerBytes": hex(&blob.header.to_bytes()),
            "signingHash": hex(&blob.header.signing_hash()),
            "signers": signers,
            "signatureBundle": hex(&blob.signatures.to_bytes()),
            "messages": blob.entries.iter().map(|e| message_json(&PriceMessage::from_bytes(&e.message_bytes).unwrap())).collect::<Vec<_>>(),
            "proofs": blob.entries.iter().map(|e| e.proof.iter().map(|p| hex(p)).collect::<Vec<_>>()).collect::<Vec<_>>(),
            "blob": hex(&blob.to_bytes()),
            "btcOnlyBlob": hex(&btc_only.to_bytes()),
        },
        "feedCell": {
            "uninitialized": hex(&PriceFeedData { feed_id: btc(), publisher_set_type_hash: set_type_hash, ..Default::default() }.to_bytes()),
            "afterBtcUpdate": hex(&feed_cell.to_bytes()),
        },
    })
}

#[test]
fn vectors_match_committed_file() {
    let actual = build();
    if std::env::var("LEAN_WRITE_VECTORS").is_ok() {
        std::fs::create_dir_all("../vectors").unwrap();
        std::fs::write(PATH, serde_json::to_string_pretty(&actual).unwrap() + "\n").unwrap();
        return;
    }
    let committed: Value = serde_json::from_str(&std::fs::read_to_string(PATH).expect("run with LEAN_WRITE_VECTORS=1 once"))
        .expect("valid JSON");
    assert_eq!(actual, committed, "Rust output differs from vectors/protocol.json");
}
