[package]
name = "price_feed_type"
version.workspace = true
edition.workspace = true

[dependencies]
ckb-std = "1.0"
lean-oracle-common = { path = "../common" }

[features]
library = []
native-simulator = ["library", "ckb-std/native-simulator"]

[[bin]]
name = "price_feed_type"
path = "src/main.rs"
